apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  #name: {{ include "hello-world.fullname" . }}
  name: example-route
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
proxy:
  path: /example
  protocol: http
route:
  methods:
    - GET
service:
  host: {{ include "hello-world.fullname" . }}
  port: {{ .Values.service.port }}
